services:
  # Chosen time-serie database: TimescaleDB on Postgres
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    volumes:
      # Persist DB data across restarts
      - tsdb-data:/var/lib/postgresql/data
      # Run our init SQL on first boot
      - ./timescaledb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      # This is database superuser credentials and db name, these are service-specific value so I don't put it into .env
      POSTGRES_USER: fitbit_user
      POSTGRES_PASSWORD: fitbit_password
      POSTGRES_DB: fitbit_data
    ports:
      - "5433:5432"

  # This is ingestion service that runs our Python + cron job (main program)
  ingester:
    env_file:
      # Pulls in .env file; these variables drive the Python script, you would need to set up .env for this ones
      - .env
    build: ./ingestion
    volumes:
      - ./ingestion/last_run.txt:/app/last_run.txt
      - ./.env:/app/.env  # for python-dotenv (optional, since env_file covers it)
    environment:
      DB_HOST: ${DB_HOST} #eg: timescaledb
      DB_PORT: ${DB_PORT} #eg: 5432
      DB_NAME: ${DB_NAME} #eg: fitbit_data
      DB_USER: ${DB_USER} #eg: fitbit_user
      DB_PASSWORD: ${DB_PASSWORD} #eg: fitbit_password
      SEED: ${SEED} #eg: 100
    depends_on:
      - timescaledb
    # Cron is configured inside the Dockerfile (via /etc/cron.d/fitbit-cron)

volumes:
  # Named volume for TimescaleDB data
  tsdb-data: