groups:
  - name: basic_alerts
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is above 80% (current value: {{ $value }}%)"

      - alert: HighAPIErrorRate
        expr: rate(api_requests_total{status=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High API error rate detected"
          description: "API error rate is {{ $value }} errors per second on {{ $labels.endpoint }}"

      - alert: SlowAPIResponse
        expr: histogram_quantile(0.95, rate(api_request_duration_seconds_bucket[5m])) > 2.0
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "Slow API responses detected"
          description: "95th percentile response time is {{ $value }}s"

      - alert: NoDataProcessing
        expr: increase(data_points_processed_total[10m]) == 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "No data processing activity"
          description: "No data points have been processed in the last 10 minutes"

      - alert: HighImputationRate
        expr: rate(imputation_operations_total[10m]) > 10
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High data imputation rate"
          description: "Imputation rate is {{ $value }} operations per second, indicating data quality issues"